**Name: Khair ul wara**  
**Lab 2**  
**Course: ANN**  
**Student Id: FA23-BAI-022**

### Task 1: Vectors

In [1]:
import numpy as np

ages = np.array([21, 34, 45, 19, 60, 28])
print("Ages vector:", ages)
print("Shape:", ages.shape)
print("Dimensions:", ages.ndim)
print("Data type:", ages.dtype)

Ages vector: [21 34 45 19 60 28]
Shape: (6,)
Dimensions: 1
Data type: int64


In [2]:
years_until_retirement = 65 - ages
print("Years until retirement:", years_until_retirement)

Years until retirement: [44 31 20 46  5 37]


In [3]:
average_age = np.mean(ages)
print("Average age:", average_age)

Average age: 34.5


### Task 2: Matrices

In [4]:
sales = np.array([
    [120, 150, 130],
    [200, 180, 210],
    [90, 100, 95],
    [300, 320, 310]
])
print(sales)
print("Shape:", sales.shape)
print("Total elements:", sales.size)

[[120 150 130]
 [200 180 210]
 [ 90 100  95]
 [300 320 310]]
Shape: (4, 3)
Total elements: 12


In [5]:
zero_matrix = np.zeros((4, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
zero_matrix[1] = [10, 20, 30]
print(zero_matrix)

[[ 0.  0.  0.]
 [10. 20. 30.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


### Task 3: Addition & Subtraction

In [7]:
term1 = np.array([
    [78, 82, 90],
    [65, 70, 60],
    [88, 95, 91]
])

term2 = np.array([
    [85, 80, 92],
    [70, 75, 68],
    [90, 93, 96]
])

print("Term 1:\n", term1)
print("Term 2:\n", term2)

Term 1:
 [[78 82 90]
 [65 70 60]
 [88 95 91]]
Term 2:
 [[85 80 92]
 [70 75 68]
 [90 93 96]]


In [8]:
combined_marks = term1 + term2
print("Combined marks (Term1 + Term2):")
print(combined_marks)

Combined marks (Term1 + Term2):
[[163 162 182]
 [135 145 128]
 [178 188 187]]


In [9]:
improvement = term2 - term1
print("Improvement (Term2 - Term1):")
print(improvement)

Improvement (Term2 - Term1):
[[ 7 -2  2]
 [ 5  5  8]
 [ 2 -2  5]]


In [10]:
total_improvement_per_student = improvement.sum(axis=1)
best_student_index = np.argmax(total_improvement_per_student)

print("Total improvement per student:", total_improvement_per_student)
print("Student with highest total improvement: Student", best_student_index + 1)

Total improvement per student: [ 7 18  5]
Student with highest total improvement: Student 2


### Task 4: Dot Product

In [11]:
item_prices = np.array([50, 20, 15, 100])
quantities = np.array([2, 5, 3, 1])

total_bill = np.dot(item_prices, quantities)
print("Total bill:", total_bill)

Total bill: 345


In [12]:
customer_quantities = np.array([
    [2, 5, 3, 1],
    [1, 2, 0, 4]
])

# For the dot product to work, the number of columns in customer_quantities (4)
# must match the number of elements in item_prices (4), since each item price
# is multiplied with the matching quantity and summed up.
total_bills = np.dot(customer_quantities, item_prices)
print("Total bill for each customer:", total_bills)

Total bill for each customer: [345 490]


### Task 5: Reshaping

In [13]:
hours_studied = np.arange(1, 13)
print("Original array:", hours_studied)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
weekly_plan = hours_studied.reshape(4, 3)
print("Reshaped into 4x3 (4 weeks, 3 days each):")
print(weekly_plan)

Reshaped into 4x3 (4 weeks, 3 days each):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
alt_shape = hours_studied.reshape(2, 6)
print("Reshaped into 2x6:")
print(alt_shape)

Reshaped into 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [16]:
try:
    invalid_shape = hours_studied.reshape(5, 3)
except ValueError as e:
    # 12 elements cannot be arranged into a 5x3 shape since 5*3=15, not 12
    print("Error:", e)

Error: cannot reshape array of size 12 into shape (5,3)


### Task 6: Indexing

In [17]:
np.random.seed(1)
matrix5 = np.random.randint(1, 51, size=(5, 5))
print(matrix5)

[[38 44 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 46  7]
 [26 21 38 19 21]
 [12 43 29 30 15]]


In [18]:
print("Element at row 3, column 4:", matrix5[2, 3])

Element at row 3, column 4: 46


In [19]:
print("Last row:", matrix5[-1])
print("Last column:", matrix5[:, -1])

Last row: [12 43 29 30 15]
Last column: [10 17  7 21 15]


In [20]:
matrix5[0, 0] = 999
print(matrix5)

[[999  44  13   9  10]
 [ 12   6  16   1  17]
 [  2  13   8  46   7]
 [ 26  21  38  19  21]
 [ 12  43  29  30  15]]


### Task 7: Slicing

In [21]:
matrix6 = np.arange(1, 37).reshape(6, 6)
print(matrix6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [22]:
top_left = matrix6[:3, :3]
print("Top-left 3x3:")
print(top_left)

Top-left 3x3:
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]


In [23]:
alternate = matrix6[::2, ::2]
print("Every alternate row and column:")
print(alternate)

Every alternate row and column:
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [24]:
last_corner = matrix6[-2:, -2:]
print("Last 2 rows and last 2 columns:")
print(last_corner)

Last 2 rows and last 2 columns:
[[29 30]
 [35 36]]


### Task 8: Random Matrices

In [25]:
seed_value = 42

np.random.seed(seed_value)
decimals = np.random.rand(3, 3)
print("Random decimals (0-1):")
print(decimals)

Random decimals (0-1):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [26]:
random_ints = np.random.randint(10, 101, size=(3, 3))
print("Random integers (10-100):")
print(random_ints)

Random integers (10-100):
[[33 12 31]
 [62 11 97]
 [39 47 11]]


In [27]:
standard_normal = np.random.randn(4, 4)
print("Standard normal 4x4:")
print(standard_normal)

Standard normal 4x4:
[[-0.46341769 -0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877 -0.2257763 ]
 [ 0.0675282  -1.42474819 -0.54438272  0.11092259]]


In [28]:
np.random.seed(seed_value)
run1 = np.random.rand(3, 3)

np.random.seed(seed_value)
run2 = np.random.rand(3, 3)

print("Run 1:\n", run1)
print("Run 2:\n", run2)
print("Identical?", np.array_equal(run1, run2))
# Both outputs are identical because resetting the same seed before each call
# makes NumPy's pseudo-random generator start from the exact same internal state

Run 1:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Run 2:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Identical? True


### Task 9: Transpose

In [29]:
performance = np.array([
    [80, 85, 88, 90, 92],
    [70, 75, 78, 74, 80],
    [95, 96, 94, 98, 97]
])
print("Original shape:", performance.shape)

Original shape: (3, 5)


In [30]:
performance_T = performance.T
print("Transposed shape:", performance_T.shape)
print(performance_T)

Transposed shape: (5, 3)
[[80 70 95]
 [85 75 96]
 [88 78 94]
 [90 74 98]
 [92 80 97]]


In [31]:
double_transpose = performance.T.T
print("Transposing twice gives back original?", np.array_equal(performance, double_transpose))

Transposing twice gives back original? True


In [32]:
matrix_a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

matrix_b = np.array([
    [1, 0],
    [0, 1],
    [1, 1]
])

result = np.dot(matrix_a, matrix_b.T)
print("Result of dot product (4x2) . (3x2).T:")
print(result)
print("Result shape:", result.shape)

Result of dot product (4x2) . (3x2).T:
[[ 1  2  3]
 [ 3  4  7]
 [ 5  6 11]
 [ 7  8 15]]
Result shape: (4, 3)
